
services:
  web:
    build: .
    container_name: hospital-control
    volumes:
      - .:/code
    command: python manage.py runserver
    depends_on:
      - db

  db: 
    image: postgres:latest
    environment:
      - POSTGRES_USER = admin
      - POSTGRES_PASSWORD = postgre1090  
      - POSTGRES_DB = hospital_control
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

