# Generated by Django 5.1.1 on 2024-10-04 07:18

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_admin', models.BooleanField(default=False, verbose_name='administrador')),
                ('is_doctor', models.BooleanField(default=False, verbose_name='medico')),
                ('is_patient', models.BooleanField(default=False, verbose_name='paciente')),
                ('is_receptionist', models.BooleanField(default=False, verbose_name='recepcionista')),
                ('birthdate', models.DateField(null=True, verbose_name='nascimento')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='cpf')),
                ('telephone', models.CharField(max_length=11, null=True, verbose_name='telefone')),
                ('adress', models.CharField(max_length=255, null=True, verbose_name='endereço')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialty', models.CharField(max_length=100, verbose_name='especialidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=100, verbose_name='Tipo de pagamento')),
                ('date', models.DateTimeField(null=True, verbose_name='Data')),
                ('hour', models.TimeField(null=True, verbose_name='Hora')),
                ('is_active', models.BooleanField(default=True, verbose_name='consulta ativa')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.doctors')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.patients')),
            ],
        ),
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cartão', 'Cartão'), ('Dinheiro', 'Dinheiro'), ('Transferecia', 'Transferecia')], default='Cartão', max_length=100, verbose_name='Tipo de pagamento')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.doctors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
