# Generated by Django 5.1.1 on 2024-10-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctors_user_alter_patients_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.users'),
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
