# Generated by Django 5.1.1 on 2024-10-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_appointment_date_alter_appointment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_type',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=100, verbose_name='status do agendamento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='type',
            field=models.CharField(max_length=100, null=True, verbose_name='tipo da consulta'),
        ),
    ]
