# Generated by Django 5.1.1 on 2024-10-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_appointment_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='user',
        ),
        migrations.AddField(
            model_name='payments',
            name='clinic_value',
            field=models.FloatField(null=True, verbose_name='valor da clínica'),
        ),
        migrations.AddField(
            model_name='payments',
            name='doctor_value',
            field=models.FloatField(null=True, verbose_name='valor do médico'),
        ),
        migrations.AddField(
            model_name='payments',
            name='value',
            field=models.FloatField(null=True, verbose_name='valor'),
        ),
    ]
