# Generated by Django 5.1.1 on 2024-10-18 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='AdminList',
        ),
        migrations.CreateModel(
            name='DoctorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.payments')),
            ],
        ),
    ]
