# Generated by Django 5.1.1 on 2024-10-21 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_list_adminlist_doctorlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='hour',
            field=models.TimeField(null=True, verbose_name='Hora'),
        ),
    ]
